var recipeName = "Creamy squash linguine";
var preperationTime = 45;
var recipeBy = "Jimmy Cutter";
var isVegetarian = true;
var calories = 223.7;
console.log('Recipe Details');
console.log('--------------');
console.log('Recipe Name:'+ recipeName);
console.log('Preperation Time:'+ preperationTime);
console.log('Recipe By:'+ recipeBy);
console.log('is Vegetarian Dish:'+ isVegetarian);
console.log('Calories:'+ calories);
var preperationTime = 60;
var recipeBy = "Jimmy Cutter George";
console.log('Recipe Details after update');
console.log('--------------');
console.log('Recipe Name:'+ recipeName);
console.log('Preperation Time:'+ preperationTime);
console.log('Recipe By:'+ recipeBy);
console.log('is Vegetarian Dish:'+ isVegetarian);
console.log('Calories:'+ calories);
